version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-NextJS-WebAdapter-Zip1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b3vqvjtcflsz"
s3_prefix = "sam-NextJS-WebAdapter-Zip1"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
